#  ___________________________________________________
# |  _____                       _____ _ _       _    |
# | |  __ \                     |  __ (_) |     | |   |
# | | |__) |__ _ __   __ _ _   _| |__) || | ___ | |_  |
# | |  ___/ _ \ '_ \ / _` | | | |  ___/ | |/ _ \| __| |
# | | |  |  __/ | | | (_| | |_| | |   | | | (_) | |_  |
# | |_|   \___|_| |_|\__, |\__,_|_|   |_|_|\___/ \__| |
# |                   __/ |                           |
# |  GNU/Linux based |___/  Multi-Rotor UAV Autopilot |
# |___________________________________________________|
#
# System Parameters Configuration File
#
# Copyright (C) 2014 Tobias Simon, Ilmenau University of Technology
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.


overo_quad: # Gumstix Overo based quadrotor
   voltage_channel: 7 # TWL4030_MADC
   current_channel: 2 # TWL4030_MADC
   adc_to_voltage: 'lambda x: (x + 27.0951) / 117.1319'
   adc_to_current: 'lambda x: 0.0303 * (2500 - x) + 0.4'
   rx_type: 'sbus' # 'sbus' or 'dsl'
   sbus_serial: # taranis sbus
      path: '/dev/ttyO0'
   dsl_serial: # ACT dsl
      path: '/dev/ttyO0'
      speed: 38400
   gpsp_serial: # GPS publisher
      path: "/dev/ttyO2"
      speed: 115200
   nrf_serial: "/dev/ttyACM0"

pi_quad: # Raspberry PI based quadrotor
   voltage_channel: 0 # currently ignored
   current_channel: 1 # currently ignored
   adc_to_voltage: 'lambda x : x * 0.003 * 3.6045'
   adc_to_current: 'lambda x : x'
   dsl_serial: # ACT DSL
      path: '/dev/ttyAMA0'
      speed: 38400
   nrf_serial: "/dev/ttyACM0"


exynos_quad: # ODROID U3 based quadrotor
   arduino_serial: # U3 IO shield serial interface
      path: '/dev/ttySAC0'
      speed: 115200
   gpsp_serial: # GPS publisher
      path: "/dev/gps0" # created by udev rule
      speed: 115200
   nrf_serial: "/dev/nrf0" # created by udev rule


aircomm:
   id: 1
   psk: "This is the PenguDog Standard Pre-Shared Key for NRF24L01+ Communication"

powerman:
   battery_cells: 4
   battery_low_cell_voltage_idle: 3.6 # [V]
   battery_low_cell_voltage_load: 3.4 # [V]
   battery_current_treshold: 3.0 # [A]
   low_voltage_hysteresis: 10.0 # [s], battery needs to go below battery_low_cell_voltage for this time period in order to trigger a low power event
   battery_capacity: 3.0 # [Ah]
 
icarus:
   takeoff:
      standard_rel_z: 4.0

   landing:
      motors_off_z: 0.4
      z_low: 0.5


rc_cal:
   pitch:
      index: -1
      min: -1.0
      max: 1.0
   roll:
      index: -1
      min: -1.0
      max: 1.0
   yaw:
      index: -1
      min: -1.0
      max: 1.0
   gas:
      index: -1
      min: -1.0
      max: 1.0
   two_state:
      index: -1
      min: -1.0
      max: 1.0
   three_state:
      index: -1
      min: -1.0
      max: 1.0


logger:
   level: 3
   details: 2


autopilot:

   main:
      acc_fg: 0.03 # accelerometer low-pass filter

   ahrs: # attitude and heading reference system
      beta: 0.041 # optimal value from madgwick paper
      beta_start: 20.0
      beta_step: 10.0

   cal: # accelerometer and magnetometer calibration
      acc_bias_x: 0.0
      acc_bias_y: 0.0
      acc_bias_z: 0.0
      acc_scale_x: 1.0
      acc_scale_y: 1.0
      acc_scale_z: 1.0
      mag_bias_x: 0.0
      mag_bias_y: 0.0
      mag_bias_z: 0.0
      mag_scale_x: 1.0
      mag_scale_y: 1.0
      mag_scale_z: 1.0

   cmc: # current magnetometer calibration
      bias: 0.0
      scale_x: 0.0
      scale_y: 0.0
      scale_z: 0.0

   inv_coupling: # enables different parts of the coupling matrix
      pitch_enabled: 1
      roll_enabled: 1
      yaw_enabled: 1

   sticks:
      pitch_roll_speed_max: 180.0 # [deg/s]
      pitch_roll_angle_max: 35.0 # [deg]
      vert_speed_max: 1.5
      horiz_speed_max: 5.0 # maximal horizontal speed
      horiz_deadzone: 0.05 # deadzone for angle and gps control
      vert_deadzone: 0.15 # if magnitude of centered gas stick is lower than this value, altitude is locked
      yaw_speed_max: 90.0 # maximum yaw rotation speed [deg/s]
      yaw_deadzone: 0.02 # yaw deadzone
      gas_acc_max: 20.0 # maximum positive/negative acceleration in m/s^2
      rotation: 0.0 # 0 = "+" mode, 90 = "x mode"
      expo: 6.0

   kalman_pos: # NEU position estimate kalman filter
      process_noise: 1.0e-6
      baro_noise: 0.01
      ultra_noise: 0.01
      gps_noise: 0.01
      use_gps_speed: 0 # use gps speed to correct estimate?

   controllers:

      stabilizing: # basic stabilizing controller:
         att_kd: 0.03929356367277829
         att_ki: 5.216018377845929
         att_kii: 1.9043325795347907
         att_kp: 0.36397715175895795
         yaw_kd: 0.0009970913130018957
         yaw_ki: 3.531770730332799
         yaw_kii: 3.8199155415521995
         yaw_kp: 0.35127751586656414
         filt_fg: 10.0
         filt_d: 0.95
         jxx_jyy: 0.0097
         jzz: 0.0057292965
         tmc: 0.03
      
      ne_speed: # north-east speed controller
         p: 2.581019276508608
         i: 1.827463461175307
         i_max: 10.0
         d: 0.0
         lpfg: 50.0

      attitude:
         p: 6.226615273654109
         i: 0.8956642009989297
         i_max: 10.0
         d: 0.5402391324294383
         pitch_bias: 0.0
         roll_bias: 0.0
         angles_max: 40.0 # maximal angle allowed in attitude control
   
      u_speed: # up speed controller (barometer)
         i: 2.0
         imax: 4.0
         p: 7.0
      
      u_pos: # ups position controller (barometer, ultrasonic)
         d: 15.563081600990635
         i: 15.563081600990635
         imax: 20.0
         p: 30.563081600990635
         lpfg: 15.0

      yaw: # yaw position controller
         pid_lim: 2.0
         p: 5.0
         d: 0.0
         i: 0.01
         i_max: 0.5

      navigation: # north-east position controller
         speed_min: 0.5
         speed_std: 2.0
         speed_max: 3.5
         sqrt_shift: 4.0
         sqrt_scale: 0.25
         square_shift: 0.2
         pos_i: 0.015
         pos_i_max: 5.0
         ortho_p: 0.0


